import { ClerkProvider, auth } from '@clerk/nextjs/app-beta'
import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <ClerkProvider>
        <body className="bg-slate-500 mx-auto">
          <header>
            <nav className="flex flex-row gap-4 p-4 border-b-2">
              <a href="/">Home</a>
              <a href="/play">Play</a>
              <a href="/sign-up">sign-up</a>
              <a href="/sign-in">sign-in</a>
            </nav>
          </header>
          {children}
        </body>
      </ClerkProvider>
    </html>
  )
}
