import { ClerkProvider, UserButton, auth } from '@clerk/nextjs/app-beta'
import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  viewport:
    'width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const { userId } = auth()

  return (
    <html lang="en">
      <ClerkProvider>
        <body className="bg-slate-100 mx-auto">
          <header>
            <nav className="w-full flex flex-row p-4 border-b-2 justify-between h-16 ">
              <div className="flex flex-row gap-4 align-middle">
                <a href="/">Home</a>
                <a href="/play">Play</a>
              </div>
              <div className="justify-self-end">
                {userId ? <UserButton /> : <a href="/sign-in">Sign in</a>}
              </div>
            </nav>
          </header>
          {children}
        </body>
      </ClerkProvider>
    </html>
  )
}
