import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="bg-slate-500">
        <header>
          <nav className="flex flex-row gap-4 p-4 bg-slate-200">
            <a href="/">Home</a>
            <a href="/play">Play</a>
          </nav>
        </header>
        {children}
      </body>
    </html>
  )
}
